[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sshpilot"
version = "3.7.6"
description = "A user-friendly, modern and lightweight SSH connection manager with an integrated terminal"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPL-3.0-only"}
authors = [{ name = "mFat", email = "newmfat@gmail.com" }]
dependencies = [
    "PyGObject>=3.42",
    "pycairo>=1.20.0",
    "paramiko>=3.4",
    "cryptography>=42.0",
    "secretstorage>=3.3; platform_system == \"Linux\"",
    "keyring>=24.3",
    "psutil>=5.9.0",
]
