name: Build Flatpak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: version
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "Building version: $VERSION"
    
    - name: Set up Flatpak environment
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak-builder

    - name: Build Flatpak with flatpak-builder
      run: |
        flatpak-builder --user --install --force-clean build-dir io.github.mfat.sshpilot.yaml

    - name: Create Flatpak bundle
      run: |
        VERSION="${GITHUB_REF#refs/tags/v}"
        BUILD_DIR="build-dir"  # Adjust to match your actual build directory
        BUNDLE_NAME="sshpilot_${VERSION}-1.flatpak"
        
        # Ensure the build directory exists
        if [ ! -d "$BUILD_DIR" ]; then
          echo "Error: Build directory not found!"
          exit 1
        fi
        
        # Create the bundle
        flatpak build-bundle $BUILD_DIR $BUNDLE_NAME --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo --arch=x86_64 io.github.mfat.sshpilot

    - name: Upload Flatpak bundle as artifact
      uses: actions/upload-artifact@v3
      with:
        name: sshpilot-flatpak
        path: "sshpilot_${VERSION}-1.flatpak"
