name: Build Debian Package

on:
  push:
    branches: [ main, dev ]
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            devscripts \
            debhelper \
            dh-python \
            python3-all \
            python3-setuptools \
            build-essential \
            git \
            fakeroot

      - name: Generate debian/changelog from __init__ version
        run: |
          VERSION=$(python3 -c "import re, pathlib; t=pathlib.Path('sshpilot/__init__.py').read_text(); print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', t).group(1))")
          echo "Detected version: ${VERSION}"
          mkdir -p debian
          {
            echo "sshpilot (${VERSION}-1) unstable; urgency=medium"
            echo
            echo "  * Various fixes and improvements"
            echo
            echo " -- mFat <newmfat@gmail.com>  $(LC_ALL=C date -R)"
          } > debian/changelog
          head -n 6 debian/changelog

      - name: Ensure Debian packaging files (if missing)
        run: |
          mkdir -p debian/source
          if [ ! -f debian/control ]; then
            cat > debian/control <<'EOF'
Source: sshpilot
Section: utils
Priority: optional
Maintainer: mFat <newmfat@gmail.com>
Build-Depends: debhelper-compat (= 13)
Standards-Version: 4.6.2
Homepage: https://github.com/mfat/sshpilot
Rules-Requires-Root: no

Package: sshpilot
Architecture: all
Depends: ${misc:Depends}, ${python3:Depends},
         python3,
         python3-gi,
         python3-gi-cairo,
         libgtk-4-1 (>= 4.6), gir1.2-gtk-4.0 (>= 4.6),
         libadwaita-1-0 (>= 1.4), gir1.2-adw-1 (>= 1.4),
         libvte-2.91-gtk4-0 (>= 0.70), gir1.2-vte-3.91 (>= 0.70),
         python3-paramiko,
         python3-cryptography,
         python3-secretstorage,
         python3-matplotlib,
         sshpass
Description: SSH connection manager with integrated terminal
 sshPilot provides SSH connection management, integrated terminal using VTE,
 tunneling, key management, and tabbed interface.
EOF
          fi
          if [ ! -f debian/rules ]; then
            cat > debian/rules <<'EOF'
#!/usr/bin/make -f
%:
	dh $@
EOF
            chmod +x debian/rules
          fi
          if [ ! -f debian/source/format ]; then
            echo '3.0 (native)' > debian/source/format
          fi

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
          mkdir -p artifacts
          mv ../*.deb artifacts/

      - name: List built packages
        run: ls -l artifacts/*.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/*.deb

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


