name: Build macOS Binary

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: mac

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install python gtk4 libadwaita vte3 adwaita-icon-theme gobject-introspection pygobject3 sshpass
          # Ensure Homebrew paths are available
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
          echo "/opt/homebrew/lib" >> $GITHUB_PATH

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko cryptography secretstorage matplotlib py2app pygobject

      - name: Set up environment for PyGObject
        run: |
          # Set environment variables for GObject Introspection
          export GI_TYPELIB_PATH=/opt/homebrew/lib/girepository-1.0
          export DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH
          echo "GI_TYPELIB_PATH=/opt/homebrew/lib/girepository-1.0" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV

      - name: Verify PyGObject installation
        run: |
          python -c "import gi; print(gi.__version__)"
          pkg-config --modversion gobject-introspection-1.0

      - name: Build app bundle
        run: python setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/*.app