name: Build macOS Binary

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15  # Latest macOS runner as of August 2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Homebrew dependencies
        run: |
          brew update
          brew install python gtk4 libadwaita vte3 adwaita-icon-theme gobject-introspection pygobject3 sshpass

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install paramiko cryptography secretstorage matplotlib
          pip install py2app

      - name: Build app bundle
        run: python setup.py py2app

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: dist/*.app