name: Build Debian Package

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-deb:
    runs-on: ubuntu-latest
    container: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        run: |
          apt-get update
          DEBIAN_FRONTEND=noninteractive apt-get install -y \
            devscripts \
            debhelper \
            dh-python \
            python3-all \
            python3-setuptools \
            build-essential \
            git \
            fakeroot

      - name: Sync changelog version/date from __init__.py
        run: |
          VERSION=$(python3 -c "import re, pathlib; t=pathlib.Path('sshpilot/__init__.py').read_text(); print(re.search(r'__version__\\s*=\\s*\"([^\"]+)\"', t).group(1))")
          echo "Detected version: ${VERSION}"
          # Update version (first line like: sshpilot (X.Y.Z-1) ...)
          sed -i -E "1 s/\(.*\)/(${VERSION}-1) unstable; urgency=medium/" debian/changelog
          # Update maintainer line date
          sed -i -E "s/^ -- .*$/ -- mFat <newmfat@gmail.com>  $(LC_ALL=C date -R)/" debian/changelog
          head -n 5 debian/changelog

      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b
          mkdir -p artifacts
          mv ../*.deb artifacts/

      - name: List built packages
        run: ls -l artifacts/*.deb

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages
          path: artifacts/*.deb

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*.deb
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
