name: Build Flatpak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4

    - name: Get version from tag
      id: version
      run: |
        # Only run on tag pushes
        if [[ "$GITHUB_REF" != refs/tags/v* ]]; then
          echo "Error: This workflow should only run on tag pushes (v* tags)"
          echo "Current ref: $GITHUB_REF"
          exit 1
        fi
        
        VERSION="${GITHUB_REF#refs/tags/v}"
        echo "version=$VERSION" >> $GITHUB_ENV
        echo "Building version: $VERSION"
    
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: sshpilot_${{ env.version }}-1.flatpak
        manifest-path: io.github.mfat.sshpilot.yaml
        cache-key: flatpak-builder-${{ github.sha }}
