name: Build macOS App

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-macos:
    runs-on: macos-13
    env:
      MACOSX_DEPLOYMENT_TARGET: '12.0'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Homebrew deps (GTK stack, GI)
        run: |
          brew update
          brew install \
            gtk4 libadwaita vte3 \
            gobject-introspection pygobject3 py3cairo \
            pkg-config

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install pyinstaller

      - name: Build app with PyInstaller
        env:
          BREW_PREFIX: $(brew --prefix)
          GI_TYPELIB_PATH: $(brew --prefix)/lib/girepository-1.0
          DYLD_FALLBACK_LIBRARY_PATH: $(brew --prefix)/opt/libadwaita/lib:$(brew --prefix)/opt/gtk4/lib:$(brew --prefix)/opt/vte3/lib:$(brew --prefix)/opt/glib/lib:$(brew --prefix)/lib
          XDG_DATA_DIRS: $(brew --prefix)/share
        run: |
          pyinstaller sshPilot.spec
          APP="dist/sshPilot.app"
          RES="$APP/Contents/Resources/app/sshpilot"
          mkdir -p "$RES/resources" "$RES/ui"
          # Include compiled GResource and UI assets expected by the app
          cp -a sshpilot/resources/sshpilot.gresource "$RES/resources/"
          cp -a sshpilot/resources/sshpilot.png "$RES/resources/" 2>/dev/null || true
          cp -a sshpilot/ui/* "$RES/ui/"
          # Include desktop metadata for reference
          cp -a io.github.mfat.sshpilot.desktop "$APP/Contents/Resources/" || true
          # Ad-hoc sign to avoid quarantine issues
          codesign --force --deep --sign - "$APP" || true

      - name: Archive app
        run: |
          cd dist
          zip -r sshPilot-macos.zip "sshPilot.app"
          shasum -a 256 sshPilot-macos.zip > sshPilot-macos.zip.sha256

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sshPilot-macos
          path: |
            dist/sshPilot-macos.zip
            dist/sshPilot-macos.zip.sha256

      - name: Attach to Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/sshPilot-macos.zip
            dist/sshPilot-macos.zip.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}