name: Build Flatpak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - name: Get version from manifest
      id: version
      run: |
        VERSION=$(grep "tag:" io.github.mfat.sshpilot.yaml | head -1 | sed 's/.*tag: v//')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Building version: $VERSION"
    
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: sshpilot_${{ steps.version.outputs.version }}-1.flatpak
        manifest-path: io.github.mfat.sshpilot.yaml
        cache-key: flatpak-builder-${{ github.sha }}