name: Build and Release Flatpak

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build (optional)'
        required: false
        type: string

env:
  FLATPAK_APP_ID: io.github.mfat.sshpilot

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Flatpak
      uses: flatpak/actions/flatpak-setup@v1
      with:
        runtime: org.gnome.Platform
        runtime-version: '48'
        sdk: org.gnome.Sdk
        sdk-version: '48'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak-builder

    - name: Build for ${{ matrix.arch }}
      run: |
        flatpak-builder --arch=${{ matrix.arch }} \
          --force-clean \
          --install-deps-from=flathub \
          --repo=repo-${{ matrix.arch }} \
          build-dir-${{ matrix.arch }} \
          io.github.mfat.sshpilot.yaml

    - name: Create bundle for ${{ matrix.arch }}
      run: |
        TAG_NAME="${{ github.ref_name || github.event.inputs.tag || 'latest' }}"
        flatpak build-bundle \
          --arch=${{ matrix.arch }} \
          --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
          repo-${{ matrix.arch }} \
          sshpilot-${TAG_NAME}-${{ matrix.arch }}.flatpak \
          ${{ env.FLATPAK_APP_ID }}

    - name: Upload x86_64 bundle
      if: matrix.arch == 'x86_64'
      uses: actions/upload-artifact@v4
      with:
        name: sshpilot-${{ matrix.arch }}
        path: sshpilot-*-${{ matrix.arch }}.flatpak

    - name: Upload aarch64 bundle
      if: matrix.arch == 'aarch64'
      uses: actions/upload-artifact@v4
      with:
        name: sshpilot-${{ matrix.arch }}
        path: sshpilot-*-${{ matrix.arch }}.flatpak

  create-release:
    runs-on: ubuntu-latest
    needs: build-and-release
    if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download bundles
      uses: actions/download-artifact@v4
      with:
        name: sshpilot-x86_64
        path: ./bundles

    - name: Download aarch64 bundle
      uses: actions/download-artifact@v4
      with:
        name: sshpilot-aarch64
        path: ./bundles

    - name: Create universal bundle
      run: |
        TAG_NAME="${{ github.ref_name || github.event.inputs.tag || 'latest' }}"
        # Use x86_64 repo as base for universal bundle
        flatpak build-bundle \
          --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
          ./bundles/repo-x86_64 \
          ./bundles/sshpilot-${TAG_NAME}-universal.flatpak \
          ${{ env.FLATPAK_APP_ID }} || \
        flatpak build-bundle \
          --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo \
          ./bundles/sshpilot-${TAG_NAME}-x86_64.flatpak \
          ./bundles/sshpilot-${TAG_NAME}-universal.flatpak \
          ${{ env.FLATPAK_APP_ID }} || echo "Universal bundle creation skipped"

    - name: Generate checksums
      run: |
        TAG_NAME="${{ github.ref_name || github.event.inputs.tag || 'latest' }}"
        cd bundles
        sha256sum sshpilot-${TAG_NAME}-*.flatpak > checksums.txt
        cat checksums.txt

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name || github.event.inputs.tag || 'latest' }}
        name: "SSHPilot ${{ github.ref_name || github.event.inputs.tag || 'latest' }}"
        body: |
          ## SSHPilot ${{ github.ref_name || github.event.inputs.tag || 'latest' }}
          
          ### Installation Instructions
          
          Choose the bundle for your architecture:
          
          **For x86_64 (Intel/AMD):**
          ```bash
          flatpak install --user sshpilot-${{ github.ref_name || github.event.inputs.tag || 'latest' }}-x86_64.flatpak
          ```
          
          **For ARM64 (Apple Silicon, ARM servers):**
          ```bash
          flatpak install --user sshpilot-${{ github.ref_name || github.event.inputs.tag || 'latest' }}-aarch64.flatpak
          ```
          
          **Universal (auto-detects architecture):**
          ```bash
          flatpak install --user sshpilot-${{ github.ref_name || github.event.inputs.tag || 'latest' }}-universal.flatpak
          ```
          
          ### Run the application
          ```bash
          flatpak run io.github.mfat.sshpilot
          ```
          
          ### Files
          - `sshpilot-${{ github.ref_name || github.event.inputs.tag || 'latest' }}-x86_64.flatpak` - Intel/AMD 64-bit
          - `sshpilot-${{ github.ref_name || github.event.inputs.tag || 'latest' }}-aarch64.flatpak` - ARM64
          - `sshpilot-${{ github.ref_name || github.event.inputs.tag || 'latest' }}-universal.flatpak` - Universal
          - `checksums.txt` - SHA256 checksums
        files: |
          bundles/sshpilot-*-x86_64.flatpak
          bundles/sshpilot-*-aarch64.flatpak
          bundles/sshpilot-*-universal.flatpak
          bundles/checksums.txt
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
