name: Windows Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install dependencies
        run: python -m pip install pytest paramiko cryptography keyring psutil pycairo
      - name: Run tests
        run: python -m pytest
